drop table if exists anime_genre;
drop table if exists anime;
drop table if exists genre;
drop table if exists type;

create table type(
    id integer primary key generated by default as identity,
    name varchar(10) unique not null);

create table anime(
    id integer primary key,
    name varchar(100) not null,
    type_id integer references type (id),
    episodes integer,
    rating numeric(4,2),
    members integer,
    constraint name_type unique(name, type_id));

create table genre(
    id integer primary key generated by default as identity,
    name varchar(20) unique not null);

create table anime_genre(
    id integer primary key generated by default as identity,
    anime_id integer not null references anime (id),
    genre_id integer not null references genre (id),
    constraint anime_genre_uc unique (anime_id, genre_id));
